// <auto-generated />
using Arsis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125113000_SetProductCommentsPendingByDefault")]
    partial class SetProductCommentsPendingByDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new AppDbContextModelSnapshot().BuildModelSnapshot(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
