// <auto-generated />
using Arsis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115093000_AddBlogs")]
    partial class AddBlogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new AppDbContextModelSnapshot().BuildModelSnapshot(modelBuilder);
        }
    }
}
