using ProjectGenerator.Core.Models;
using Newtonsoft.Json;

namespace ProjectGenerator.Core.Generators;

public class SeedDataGenerator
{
    private readonly ProjectConfig _config;

    public SeedDataGenerator(ProjectConfig config)
    {
        _config = config;
    }

    public void Generate()
    {
        Console.WriteLine("Generating comprehensive seed data configuration...");

        var infrastructurePath = Path.Combine(_config.OutputPath, "src", "Infrastructure");
        var seedDataPath = Path.Combine(infrastructurePath, "Data", "SeedData");
        var migrationsPath = Path.Combine(infrastructurePath, "Data", "Migrations");
        
        Directory.CreateDirectory(seedDataPath);
        Directory.CreateDirectory(migrationsPath);

        // Generate seed data class with all entities
        GenerateSeedDataClass(seedDataPath);

        // Generate initial migration
        GenerateInitialMigration(migrationsPath);

        // Generate JSON configuration files
        GenerateSeedDataJson(seedDataPath);

        // Generate default seed data if not provided
        GenerateDefaultSeedData();

        Console.WriteLine("✓ Comprehensive seed data configuration created");
    }

    private void GenerateSeedDataClass(string seedDataPath)
    {
        var content = $@"using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using {_config.Namespace}.Domain.Entities;
using {_config.Namespace}.Infrastructure.Persistence;

namespace {_config.Namespace}.Infrastructure.Persistence.SeedData;

public class DatabaseSeeder
{{
    private readonly ApplicationDbContext _context;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;
    private readonly IConfiguration _configuration;

    public DatabaseSeeder(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager,
        IConfiguration configuration)
    {{
        _context = context;
        _userManager = userManager;
        _roleManager = roleManager;
        _configuration = configuration;
    }}

    public async Task SeedAsync()
    {{
        // Ensure database is created
        await _context.Database.EnsureCreatedAsync();

        // Seed Roles
        await SeedRolesAsync();

        // Seed Users
        await SeedUsersAsync();

        await _context.SaveChangesAsync();
    }}

    private async Task SeedRolesAsync()
    {{
        var roles = new[] {{ ""Admin"", ""User"", ""Seller"" }};

        foreach (var roleName in roles)
        {{
            if (!await _roleManager.RoleExistsAsync(roleName))
            {{
                await _roleManager.CreateAsync(new IdentityRole(roleName));
            }}
        }}
    }}

    private async Task SeedUsersAsync()
    {{
        // Seed Admin User
        var adminEmail = _configuration[""SeedData:AdminEmail""] ?? ""admin@example.com"";
        var adminPhone = _configuration[""SeedData:AdminPhone""] ?? ""09123456789"";
        var adminPassword = _configuration[""SeedData:AdminPassword""] ?? ""Admin@123"";

        var adminUser = await _userManager.FindByEmailAsync(adminEmail);
        if (adminUser == null)
        {{
            adminUser = new ApplicationUser
            {{
                UserName = adminPhone,
                Email = adminEmail,
                PhoneNumber = adminPhone,
                PhoneNumberConfirmed = true,
                EmailConfirmed = true
            }};

            var result = await _userManager.CreateAsync(adminUser, adminPassword);
            if (result.Succeeded)
            {{
                await _userManager.AddToRoleAsync(adminUser, ""Admin"");
            }}
        }}

        // Note: Additional users can be seeded from appsettings.json or users.json file
        // For now, only the admin user is seeded. You can extend this method to read from configuration.
    }}
}}
";

        File.WriteAllText(Path.Combine(seedDataPath, "DatabaseSeeder.cs"), content);
    }

    private void GenerateInitialMigration(string migrationsPath)
    {
        var content = $@"using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace {_config.Namespace}.Infrastructure.Persistence.Migrations;

public partial class InitialCreate : Migration
{{
    protected override void Up(MigrationBuilder migrationBuilder)
    {{
        // This migration will be generated by EF Core
        // Run: dotnet ef migrations add InitialCreate
        // Then: dotnet ef database update
    }}

    protected override void Down(MigrationBuilder migrationBuilder)
    {{
        // Drop all tables
    }}
}}
";

        File.WriteAllText(Path.Combine(migrationsPath, "InitialCreate.cs"), content);
    }

    private void GenerateSeedDataJson(string seedDataPath)
    {
        // Generate roles.json
        var rolesJson = JsonConvert.SerializeObject(_config.Options.SeedRoles, Formatting.Indented);
        File.WriteAllText(Path.Combine(seedDataPath, "roles.json"), rolesJson);

        // Generate users.json
        var usersJson = JsonConvert.SerializeObject(_config.Options.SeedUsers, Formatting.Indented);
        File.WriteAllText(Path.Combine(seedDataPath, "users.json"), usersJson);

        // Generate permissions.json
        var permissionsJson = JsonConvert.SerializeObject(_config.Options.SeedPermissions, Formatting.Indented);
        File.WriteAllText(Path.Combine(seedDataPath, "permissions.json"), permissionsJson);

        if (_config.Options.Features.ProductCatalog)
        {
            // Generate categories.json
            var categoriesJson = JsonConvert.SerializeObject(_config.Options.SeedCategories, Formatting.Indented);
            File.WriteAllText(Path.Combine(seedDataPath, "categories.json"), categoriesJson);

            // Generate products.json
            var productsJson = JsonConvert.SerializeObject(_config.Options.SeedProducts, Formatting.Indented);
            File.WriteAllText(Path.Combine(seedDataPath, "products.json"), productsJson);
        }

        if (_config.Options.Features.SellerPanel)
        {
            // Generate sellers.json
            var sellersJson = JsonConvert.SerializeObject(_config.Options.SeedSellers, Formatting.Indented);
            File.WriteAllText(Path.Combine(seedDataPath, "sellers.json"), sellersJson);
        }

        if (_config.Options.Features.BlogSystem)
        {
            // Generate blog-categories.json
            var blogCategoriesJson = JsonConvert.SerializeObject(_config.Options.SeedBlogCategories, Formatting.Indented);
            File.WriteAllText(Path.Combine(seedDataPath, "blog-categories.json"), blogCategoriesJson);

            // Generate blog-posts.json
            var blogPostsJson = JsonConvert.SerializeObject(_config.Options.SeedBlogPosts, Formatting.Indented);
            File.WriteAllText(Path.Combine(seedDataPath, "blog-posts.json"), blogPostsJson);
        }

        // Generate site-settings.json
        var siteSettingsJson = JsonConvert.SerializeObject(_config.Options.SeedSiteSettings, Formatting.Indented);
        File.WriteAllText(Path.Combine(seedDataPath, "site-settings.json"), siteSettingsJson);

        // Generate navigation-menu.json
        var navigationMenuJson = JsonConvert.SerializeObject(new List<object>(), Formatting.Indented);
        File.WriteAllText(Path.Combine(seedDataPath, "navigation-menu.json"), navigationMenuJson);
    }

    private void GenerateDefaultSeedData()
    {
        // Generate default seed data if lists are empty
        if (!_config.Options.SeedRoles.Any())
        {
            _config.Options.SeedRoles.AddRange(new[]
            {
                new SeedRole { Name = "Admin", Description = "Administrator role with full access", Permissions = new List<string>() },
                new SeedRole { Name = "Seller", Description = "Seller role with product management access", Permissions = new List<string>() },
                new SeedRole { Name = "User", Description = "Regular user role", Permissions = new List<string>() }
            });
        }

        if (!_config.Options.SeedUsers.Any())
        {
            _config.Options.SeedUsers.Add(new SeedUser
            {
                Username = "admin",
                Email = "admin@example.com",
                PhoneNumber = "09123456789",
                Password = "Admin@123",
                Roles = new List<string> { "Admin" }
            });
        }

        if (_config.Options.Features.ProductCatalog && !_config.Options.SeedCategories.Any() && _config.Options.SeedData.SeedCategories)
        {
            _config.Options.SeedCategories.AddRange(new[]
            {
                new SeedCategory { Name = "الکترونیک", Slug = "electronics", Description = "دسته‌بندی محصولات الکترونیک" },
                new SeedCategory { Name = "پوشاک", Slug = "clothing", Description = "دسته‌بندی پوشاک" },
                new SeedCategory { Name = "کتاب", Slug = "books", Description = "دسته‌بندی کتاب‌ها" }
            });
        }

        if (_config.Options.Features.BlogSystem && !_config.Options.SeedBlogCategories.Any() && _config.Options.SeedData.SeedBlogCategories)
        {
            _config.Options.SeedBlogCategories.AddRange(new[]
            {
                new SeedBlogCategory { Name = "عمومی", Slug = "general", Description = "دسته‌بندی عمومی" },
                new SeedBlogCategory { Name = "فناوری", Slug = "technology", Description = "دسته‌بندی فناوری" }
            });
        }

        if (!_config.Options.SeedSiteSettings.Any() && _config.Options.SeedData.SeedSiteSettings)
        {
            _config.Options.SeedSiteSettings.AddRange(new[]
            {
                new SeedSiteSetting { Key = "SiteName", Value = _config.Theme.SiteName, Description = "نام سایت" },
                new SeedSiteSetting { Key = "SiteDescription", Value = _config.Theme.SiteDescription, Description = "توضیحات سایت" },
                new SeedSiteSetting { Key = "ContactEmail", Value = "info@example.com", Description = "ایمیل تماس" },
                new SeedSiteSetting { Key = "ContactPhone", Value = "021-12345678", Description = "تلفن تماس" }
            });
        }
    }
}